<a href="https://colab.research.google.com/github/tusharadi25/MF_suggestions/blob/master/MF_withDrawSuggestions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# from google.colab import drive
# drive.mount('/content/gdrive')
# df = pd.read_csv('/content/gdrive/My Drive/MF/AxisBluechipDirect.csv')
import pandas as pd
raw_git_CSV_path='https://raw.githubusercontent.com/tusharadi25/MF_suggestions/master/AxisBluechipDirect.csv'
df=pd.read_csv(raw_git_CSV_path)

In [2]:
print(df)

     plan_code        Plan_Name  NAV_Value    NAV_Date
0           D1  Direct Dividend      12.18  01-01-2013
1           D1  Direct Dividend      12.28  02-01-2013
2           D1  Direct Dividend      12.32  03-01-2013
3           D1  Direct Dividend      12.35  04-01-2013
4           D1  Direct Dividend      12.28  07-01-2013
...        ...              ...        ...         ...
8211        GP           Growth      31.45  01-11-2019
8212        GP           Growth      31.57  04-11-2019
8213        GP           Growth      31.55  05-11-2019
8214        GP           Growth      31.64  06-11-2019
8215        GP           Growth      31.76  07-11-2019

[8216 rows x 4 columns]

In [3]:
df=df.loc[df['plan_code'] == 'DG']
print(df)

     plan_code      Plan_Name  NAV_Value    NAV_Date
1684        DG  Direct Growth      12.18  01-01-2013
1685        DG  Direct Growth      12.28  02-01-2013
1686        DG  Direct Growth      12.32  03-01-2013
1687        DG  Direct Growth      12.35  04-01-2013
1688        DG  Direct Growth      12.28  07-01-2013
...        ...            ...        ...         ...
3363        DG  Direct Growth      34.06  01-11-2019
3364        DG  Direct Growth      34.20  04-11-2019
3365        DG  Direct Growth      34.18  05-11-2019
3366        DG  Direct Growth      34.28  06-11-2019
3367        DG  Direct Growth      34.41  07-11-2019

[1684 rows x 4 columns]

In [4]:
data=dict(zip(df.NAV_Date,df.NAV_Value))
print(list(data.items())[:5])

[('01-01-2013', 12.18), ('02-01-2013', 12.28), ('03-01-2013', 12.32), ('04-01-2013', 12.35), ('07-01-2013', 12.28)]

In [5]:
filterDict={}
for date in data.keys():
  filterDict[date[3:]]={}
for date in data.keys():
  filterDict[date[3:]][date[:2]]=data.get(date)
print(list(filterDict.items())[:5])

[('01-2013', {'01': 12.18, '02': 12.28, '03': 12.32, '04': 12.35, '07': 12.28, '08': 12.34, '09': 12.28, '10': 12.29, '11': 12.25, '14': 12.37, '15': 12.41, '16': 12.28, '17': 12.33, '18': 12.4, '21': 12.39, '22': 12.33, '23': 12.33, '24': 12.26, '25': 12.39, '28': 12.39, '29': 12.34, '30': 12.36, '31': 12.33}), ('02-2013', {'01': 12.28, '04': 12.3, '05': 12.24, '06': 12.25, '07': 12.22, '08': 12.19, '11': 12.14, '12': 12.19, '13': 12.24, '14': 12.21, '15': 12.23, '18': 12.23, '19': 12.28, '20': 12.3, '21': 12.19, '22': 12.16, '25': 12.18, '26': 12.06, '27': 12.1, '28': 11.96}), ('03-2013', {'01': 12.02, '04': 12.0, '05': 12.13, '06': 12.18, '07': 12.26, '08': 12.4, '11': 12.42, '12': 12.38, '13': 12.27, '14': 12.37, '15': 12.32, '18': 12.27, '19': 12.16, '20': 12.04, '21': 12.01, '22': 11.96, '25': 11.96, '26': 12.04, '28': 12.14}), ('04-2013', {'01': 12.16, '02': 12.27, '03': 12.19, '04': 12.01, '05': 11.98, '08': 11.97, '09': 11.91, '10': 12.02, '11': 12.11, '12': 12.0, '15': 12.04, '16': 12.3, '17': 12.31, '18': 12.49, '22': 12.64, '23': 12.61, '25': 12.77, '26': 12.67, '29': 12.71, '30': 12.77}), ('05-2013', {'02': 12.9, '03': 12.8, '06': 12.84, '07': 12.93, '08': 13.02, '09': 12.99, '10': 13.07, '13': 12.86, '14': 12.89, '15': 13.14, '16': 13.14, '17': 13.14, '20': 13.08, '21': 13.01, '22': 13.0, '23': 12.81, '24': 12.82, '27': 12.98, '28': 13.09, '29': 13.11, '30': 13.16, '31': 12.93})]

In [6]:
import operator
for month in filterDict.keys():
  base_Nav=0
  for day in filterDict[month].keys():
    if base_Nav is 0:
      base_Nav=filterDict[month][day]
    filterDict[month][day]-=base_Nav

print(list(filterDict.items())[:5])

[('01-2013', {'01': 0.0, '02': 0.09999999999999964, '03': 0.14000000000000057, '04': 0.16999999999999993, '07': 0.09999999999999964, '08': 0.16000000000000014, '09': 0.09999999999999964, '10': 0.10999999999999943, '11': 0.07000000000000028, '14': 0.1899999999999995, '15': 0.23000000000000043, '16': 0.09999999999999964, '17': 0.15000000000000036, '18': 0.22000000000000064, '21': 0.21000000000000085, '22': 0.15000000000000036, '23': 0.15000000000000036, '24': 0.08000000000000007, '25': 0.21000000000000085, '28': 0.21000000000000085, '29': 0.16000000000000014, '30': 0.17999999999999972, '31': 0.15000000000000036}), ('02-2013', {'01': 0.0, '04': 0.02000000000000135, '05': -0.03999999999999915, '06': -0.02999999999999936, '07': -0.05999999999999872, '08': -0.08999999999999986, '11': -0.1399999999999988, '12': -0.08999999999999986, '13': -0.03999999999999915, '14': -0.06999999999999851, '15': -0.049999999999998934, '18': -0.049999999999998934, '19': 0.0, '20': 0.02000000000000135, '21': -0.08999999999999986, '22': -0.11999999999999922, '25': -0.09999999999999964, '26': -0.21999999999999886, '27': -0.17999999999999972, '28': -0.3199999999999985}), ('03-2013', {'01': 0.0, '04': -0.019999999999999574, '05': 0.11000000000000121, '06': 0.16000000000000014, '07': 0.2400000000000002, '08': 0.3800000000000008, '11': 0.40000000000000036, '12': 0.3600000000000012, '13': 0.25, '14': 0.34999999999999964, '15': 0.3000000000000007, '18': 0.25, '19': 0.14000000000000057, '20': 0.019999999999999574, '21': -0.009999999999999787, '22': -0.05999999999999872, '25': -0.05999999999999872, '26': 0.019999999999999574, '28': 0.120000000000001}), ('04-2013', {'01': 0.0, '02': 0.10999999999999943, '03': 0.02999999999999936, '04': -0.15000000000000036, '05': -0.17999999999999972, '08': -0.1899999999999995, '09': -0.25, '10': -0.14000000000000057, '11': -0.05000000000000071, '12': -0.16000000000000014, '15': -0.120000000000001, '16': 0.14000000000000057, '17': 0.15000000000000036, '18': 0.33000000000000007, '22': 0.4800000000000004, '23': 0.4499999999999993, '25': 0.6099999999999994, '26': 0.5099999999999998, '29': 0.5500000000000007, '30': 0.6099999999999994}), ('05-2013', {'02': 0.0, '03': -0.09999999999999964, '06': -0.0600000000000005, '07': 0.02999999999999936, '08': 0.11999999999999922, '09': 0.08999999999999986, '10': 0.16999999999999993, '13': -0.040000000000000924, '14': -0.009999999999999787, '15': 0.2400000000000002, '16': 0.2400000000000002, '17': 0.2400000000000002, '20': 0.17999999999999972, '21': 0.10999999999999943, '22': 0.09999999999999964, '23': -0.08999999999999986, '24': -0.08000000000000007, '27': 0.08000000000000007, '28': 0.1899999999999995, '29': 0.20999999999999908, '30': 0.2599999999999998, '31': 0.02999999999999936})]

In [10]:
dist={}
for month in filterDict.keys():
  high=0
  highDate=0
  for day in filterDict[month].keys():
    if high < filterDict[month][day]:
      high = filterDict[month][day]
      highDate=int(day)
  dist[month]=highDate
print(dist)

{'01-2013': 15, '02-2013': 4, '03-2013': 11, '04-2013': 25, '05-2013': 30, '06-2013': 0, '07-2013': 15, '08-2013': 14, '09-2013': 19, '10-2013': 31, '11-2013': 0, '12-2013': 31, '01-2014': 0, '02-2014': 28, '03-2014': 31, '04-2014': 23, '05-2014': 23, '06-2014': 30, '07-2014': 7, '08-2014': 27, '09-2014': 19, '10-2014': 31, '11-2014': 28, '12-2014': 4, '01-2015': 27, '02-2015': 19, '03-2015': 3, '04-2015': 13, '05-2015': 29, '06-2015': 25, '07-2015': 22, '08-2015': 6, '09-2015': 21, '10-2015': 23, '11-2015': 3, '12-2015': 31, '01-2016': 0, '02-2016': 0, '03-2016': 31, '04-2016': 27, '05-2016': 31, '06-2016': 8, '07-2016': 28, '08-2016': 31, '09-2016': 8, '10-2016': 5, '11-2016': 0, '12-2016': 9, '01-2017': 27, '02-2017': 21, '03-2017': 30, '04-2017': 26, '05-2017': 31, '06-2017': 19, '07-2017': 31, '08-2017': 31, '09-2017': 19, '10-2017': 16, '11-2017': 28, '12-2017': 29, '01-2018': 29, '02-2018': 0, '03-2018': 0, '04-2018': 30, '05-2018': 31, '06-2018': 15, '07-2018': 31, '08-2018': 28, '09-2018': 0, '10-2018': 0, '11-2018': 30, '12-2018': 19, '01-2019': 0, '02-2019': 7, '03-2019': 29, '04-2019': 30, '05-2019': 31, '06-2019': 0, '07-2019': 4, '08-2019': 9, '09-2019': 23, '10-2019': 31, '11-2019': 7}

In [0]:
def findCounts(arr, n): 
    i = 0
    while i<n: 
        if arr[i] <= 0: 
            i += 1
            continue
        elementIndex = arr[i] - 1
        if arr[elementIndex] > 0: 
            arr[i] = arr[elementIndex] 
            arr[elementIndex] = -1 
        else: 
            arr[elementIndex] -= 1
            arr[i] = 0
            i += 1
  
    print ("Below are counts of all elements") 
    for i in range(0,n): 
        print ("%d -> %d"%(i+1, abs(arr[i]))) 
    print ("")

In [12]:

findCounts(list(dist.values()),31) 
print(dist)

Below are counts of all elements
1 -> 0
2 -> 0
3 -> 1
4 -> 2
5 -> 0
6 -> 0
7 -> 1
8 -> 0
9 -> 0
10 -> 0
11 -> 1
12 -> 0
13 -> 1
14 -> 1
15 -> 2
16 -> 0
17 -> 0
18 -> 0
19 -> 3
20 -> 0
21 -> 0
22 -> 1
23 -> 2
24 -> 0
25 -> 2
26 -> 0
27 -> 2
28 -> 2
29 -> 1
30 -> 2
31 -> 4

{'01-2013': 15, '02-2013': 4, '03-2013': 11, '04-2013': 25, '05-2013': 30, '06-2013': 0, '07-2013': 15, '08-2013': 14, '09-2013': 19, '10-2013': 31, '11-2013': 0, '12-2013': 31, '01-2014': 0, '02-2014': 28, '03-2014': 31, '04-2014': 23, '05-2014': 23, '06-2014': 30, '07-2014': 7, '08-2014': 27, '09-2014': 19, '10-2014': 31, '11-2014': 28, '12-2014': 4, '01-2015': 27, '02-2015': 19, '03-2015': 3, '04-2015': 13, '05-2015': 29, '06-2015': 25, '07-2015': 22, '08-2015': 6, '09-2015': 21, '10-2015': 23, '11-2015': 3, '12-2015': 31, '01-2016': 0, '02-2016': 0, '03-2016': 31, '04-2016': 27, '05-2016': 31, '06-2016': 8, '07-2016': 28, '08-2016': 31, '09-2016': 8, '10-2016': 5, '11-2016': 0, '12-2016': 9, '01-2017': 27, '02-2017': 21, '03-2017': 30, '04-2017': 26, '05-2017': 31, '06-2017': 19, '07-2017': 31, '08-2017': 31, '09-2017': 19, '10-2017': 16, '11-2017': 28, '12-2017': 29, '01-2018': 29, '02-2018': 0, '03-2018': 0, '04-2018': 30, '05-2018': 31, '06-2018': 15, '07-2018': 31, '08-2018': 28, '09-2018': 0, '10-2018': 0, '11-2018': 30, '12-2018': 19, '01-2019': 0, '02-2019': 7, '03-2019': 29, '04-2019': 30, '05-2019': 31, '06-2019': 0, '07-2019': 4, '08-2019': 9, '09-2019': 23, '10-2019': 31, '11-2019': 7}